#!/bin/bash
HELP="deploy script for AAPB and OpenVault3"

IMAGE_NAME=aapb-deploy

VOLUME_MOUNT="-v `pwd`:/root/"
DOCKER_ARGS="docker run -it $VOLUME_MOUNT"

if [ -z $1 -o $1 = "help" -o $1 = "h" ]; then
    echo -e $HELP

elif [ $1 = "build" -o $1 = "b" ]; then
    shift
    # build the docker image
    docker build -t $IMAGE_NAME . "$@"

elif [ $1 = "aapb" -o $1 = "aapb-demo" ]; then
    shift
    # deploy aapb
    $DOCKER_ARGS \
    -e BRANCH=24-og-timestamps \
    -e APP_NAME=aapb \
    -e REPO_URL=https://github.com/WGBH-MLA/AAPB2.git \
    -e SSH_HOST=18.213.230.80 \
    -e SSH_KEY=/root/aapb.wgbh-mla.org.pem \
    $IMAGE_NAME "$@"

elif [ $1 = "openvault" -o $1 = "openvault-demo" ]; then
    shift
    # OpenVault deploy
else 
    echo -e "$1 command not recognized\n"
    echo "$@"
    echo -e $HELP
fi
