#!/bin/bash
HELP="deploy script for AAPB and OpenVault3"

IMAGE_NAME=aapb-deploy

VOLUME_MOUNT="-v `pwd`:/root/"
DOCKER_ARGS="docker run -it $VOLUME_MOUNT"

if [ -z $1 -o $1 = "help" -o $1 = "h" ]; then
    echo -e $HELP

elif [ $1 = "build" -o $1 = "b" ]; then
    shift
    # build the docker image
    docker build -t $IMAGE_NAME . "$@"

elif [ $1 = "deploy" ]; then
    shift
    # deploy aapb
    $DOCKER_ARGS \
    -e BRANCH \
    -e APP_NAME \
    -e REPO_URL \
    -e SSH_HOST \
    -e SSH_KEY \
    $IMAGE_NAME "$@"

else 
    echo -e "$1 command not recognized\n"
    echo "$@"
    echo -e $HELP
fi
